WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E1BDF6DB50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c2003ede56784ea5331ba1890ba8d66f
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E1BDF20B10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c2003ede56784ea5331ba1890ba8d66f
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E1BDF6E810>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c2003ede56784ea5331ba1890ba8d66f