WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CBEA83B150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b3c03a8aecb99e0800a317a7742b992c
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CBEA7E0B10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b3c03a8aecb99e0800a317a7742b992c
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CBEA83BE90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b3c03a8aecb99e0800a317a7742b992c